### ISSUE TITLE
IDK why this error

### ISSUE THREAD

**Issue by varvorvir** [GabrielAgrela/OSROKBOT#13]
![Screenshot 2023-11-30 101336](https://github.com/GabrielAgrela/OSROKBOT/assets/152460935/7b0ba1de-e0cf-4693-ae8e-fe58b3f0ffec)
 
Idk why this error, cant you help me

**Comment by dualkeyboards** [comment]
may be try running the game with 720p res?

**Comment by varvorvir** [comment]
> may be try running the game with 720p res?

i am already make it 720 but bot still cant run, idk why

**Comment by JefIra24** [comment]
> i am already make it 720 but bot still cant run, idk why

Do you use English in the game? if you haven't tried it, do it

**Comment by varvorvir** [comment]
> > i am already make it 720 but bot still cant run, idk why
> 
> Do you use English in the game? if you haven't tried it, do it

yes, my game is english

**Comment by GabrielAgrela** [comment]
Don't run it through the command prompt. Run it through your IDE, it works on VSCode.

**Comment by GabrielAgrela** [comment]
You need to install the missing libraries with pip install. @varvorvir 

Tutorial added in readme.
