### ISSUE TITLE
where is the OPENAI_KEY?

### ISSUE THREAD

**Issue by Vince069** [GabrielAgrela/OSROKBOT#27]
Good morning.
First of all, thank you for this video.
I'm stuck at the step concerning the OPENAI_KEY.
Where do we find the latter?
thanks in advance

**Comment by vw-joker** [comment]
Assuming you mean where to get an API key to put into your .env file?

https://help.openai.com/en/articles/4936850-where-do-i-find-my-openai-api-key
https://platform.openai.com/api-keys

... and a bit of a "how to" https://wedevs.com/blog/483810/generate-chatgpt-api-key/
