### ISSUE TITLE
Running bot the functionality don't work

### ISSUE THREAD

**Issue by xmtzkx** [GabrielAgrela/OSROKBOT#29]
The program is running but it does not do what should be done. It does not click the icons etc. How to fix this?

![image](https://github.com/user-attachments/assets/208b929a-086d-4462-ab0e-606675ee1d51)

**Comment by vw-joker** [comment]
Try running Visual Studio as Administrator.

**Comment by xmtzkx** [comment]
Ohh thanks, I forgot to run it as admin.
