### ISSUE TITLE
как запустить бота?

### ISSUE THREAD

**Issue by David-tilda** [GabrielAgrela/OSROKBOT#4]
пока не понятно как запустить... появляется ошибка cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

**Comment by GabrielAgrela** [comment]
Tutorial added in readme
