### ISSUE TITLE
About ChatGPT

### ISSUE THREAD

**Issue by aleshamail** [GabrielAgrela/OSROKBOT#5]
If bot didn't find the correct answer, then in theory it should look for the ChatGPT answer, but this does not happen. Help))

Example:
Most similar entry 'A robot may not injure a human being or through inaction allow a human being to come to harm. Which of Isaac Asimovs Three Laws of Robotics is this?' has a similarity score of: 0.8679 with
Most similar entry 'Mauritius' has a similarity score of: 0.5740 with

D is the closest match
with : 0.8679417063560892

Press k to for the next question

**Comment by GabrielAgrela** [comment]
Did you add your openai api key do the .env?

**Comment by aleshamail** [comment]
> Did you add your openai api key to the .env?

Yes)

**Comment by GabrielAgrela** [comment]
All right. Where you using it for the midterm? And if so, did the mouse hover over the option D?

**Comment by aleshamail** [comment]
Yes> midterm. Mouse moved on D

**Comment by aleshamail** [comment]
Oh nevermind)) Your Bot is very nice without ChatGPT too))))

**Comment by GabrielAgrela** [comment]
Thanks! I pushed the fixed code into GitHub, it should work now when you pull it. I can't test it now since there is no lyceum available, only monday.

**Comment by aleshamail** [comment]
Wow so fast) Thank you very much!!!!!!!!!!!!!!!

**Comment by aleshamail** [comment]
I checked. It works. But I have a key for version 3.5))) And the bot requires version gpt-4)))))))))))))) 
Thank you so much again!!!

**Comment by GabrielAgrela** [comment]
in chatgpt_action.py, where it says 

```
def execute(self):
        #os.system('cls')
        self.message = "Question:" +  GlobalVars().Q + "\n" + "A:" + GlobalVars().A + "\n" + "B:" + GlobalVars().B + "\n" + "C:" + GlobalVars().C + "\n" + "D:" + GlobalVars().D
        print("\n\n")
        self.messages.append({"role": "user", "content": (self.message)},)
        chat = openai.ChatCompletion.create(
            model="gpt-4",
            temperature=.1,
            messages=self.messages,
            functions=self.functions,
            function_call={"name": "return_option_based_on_prompt"}
        )
```

you can put gpt-3.5-turbo

**Comment by aleshamail** [comment]
Awesome!!!
═══════════════
▄██▄██▄░░░㋡ ♥ ㋡
▀█████▀░░░/♥\./█\
░░▀█▀░░░░░ .||.   .||.
═══════════════
