### ISSUE TITLE
how to handle it

### ISSUE THREAD

**Issue by JefIra24** [GabrielAgrela/OSROKBOT#9]
![Untitled](https://github.com/GabrielAgrela/OSROKBOT/assets/109614579/d1218dbc-a9c2-4cce-a83b-acda2e3f9083)
i am having this kind of problem...please help me please

**Comment by dualkeyboards** [comment]
go back to your root dir, and edit .env change ANTIALIAS_METHOD to LANCZOS
the reason is ANTIALIAS is obsolete

**Comment by JefIra24** [comment]
> go back to your root dir, and edit .env change ANTIALIAS_METHOD to LANCZOS the reason is ANTIALIAS is obsolete

my problem has been resolved...
how do I run it now??

**Comment by JefIra24** [comment]
![Untitled](https://github.com/GabrielAgrela/OSROKBOT/assets/109614579/cd4cc863-3d01-45a8-b87d-03aae05cf1c4)

![1111](https://github.com/GabrielAgrela/OSROKBOT/assets/109614579/fcd6f229-8fd8-4b3b-b07b-041393fc89cb)


I tried running it... but it didn't work...

Am I doing something wrong?

please provide a tutorial to run it properly.. thank you

**Comment by GabrielAgrela** [comment]
Are you running vscode as administrator?

**Comment by JefIra24** [comment]
> Are you running vscode as administrator?

thanks for the answer... works perfectly..

**Comment by GabrielAgrela** [comment]
No worries! My bad, I thought I had mentioned it the ReadMe. Updated now.

**Comment by JefIra24** [comment]
I still have questions for more problems...

Below I include my screenshot..
Please help

![Uploading 1111.png…]()
![Uploading Untitled.png…]()
